version: '3.1'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app:delegated
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: mariadb
        restart: always
        ports:
            - ${DBPORT}:${DBPORT}
        volumes:
            - "./mysql:/var/lib/mysql"
            - "./initdb.d:/docker-entrypoint-initdb.d"
        environment:
            - MYSQL_ROOT_PASSWORD=${ROOTPASS}
            - MYSQL_DATABASE=${DATABASE}
            - MYSQL_USER=${USERNAME}
            - MYSQL_PASSWORD=${USERPASS}
 
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080