# Generated by Django 3.2.4 on 2021-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterator_trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='gender',
            field=models.IntegerField(choices=[(0, 'All'), (1, 'Men'), (2, 'Women')], default=0, max_length=11),
        ),
        migrations.RunSQL(
            """
                ALTER TABLE iterator_trial_subcategory CHANGE COLUMN gender gender int(11) NOT NULL DEFAULT 0 AFTER name
            """
        )
    ]
